name: 编译PDF转Excel安卓APP

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 90
    
    steps:
    - name: 检出代码
      uses: actions/checkout@v3
    
    - name: 设置Python环境
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: 安装系统依赖
      run: |
        sudo apt-get update
        sudo apt-get install -y openjdk-8-jdk autoconf libtool pkg-config \
          zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake \
          libffi-dev libssl-dev build-essential python3-dev
    
    - name: 设置Java环境
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
    
    - name: 安装Python依赖
      run: |
        python -m pip install --upgrade pip
        pip install buildozer cython kivy pandas pdfplumber openpyxl xlsxwriter
    
    - name: 准备编译文件
      run: |
        cp android_app.py main.py
        echo "文件准备完成"
        ls -la
    
    - name: 缓存buildozer依赖
      uses: actions/cache@v3
      with:
        path: |
          ~/.buildozer
        key: buildozer-cache-${{ runner.os }}-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          buildozer-cache-${{ runner.os }}-
    
    - name: 编译APK
      run: |
        echo "开始编译Android APK..."
        buildozer android debug --verbose
        echo "编译完成"
    
    - name: 验证编译结果
      run: |
        if [ -f bin/*.apk ]; then
          echo "APK编译成功！"
          ls -la bin/
          echo "文件大小: $(du -h bin/*.apk)"
        else
          echo "APK编译失败"
          ls -la
          exit 1
        fi
    
    - name: 重命名APK文件
      run: |
        cd bin
        mv *.apk pdf-excel-converter.apk
        echo "APK文件已重命名为 pdf-excel-converter.apk"
    
    - name: 上传APK文件
      uses: actions/upload-artifact@v3
      with:
        name: pdf-excel-android-app
        path: bin/pdf-excel-converter.apk
        retention-days: 90
    
    - name: 创建Release
      if: github.ref == 'refs/heads/main'
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: v1.0-${{ github.run_number }}
        release_name: PDF转Excel安卓APP v1.0-${{ github.run_number }}
        body: |
          PDF转Excel转换工具安卓版本
          
          功能特性:
          - PDF文件转Excel格式
          - 自动删除指定列
          - 数据排序和格式化
          - 时间格式优化
          - 列宽自动调整
          
          支持系统: Android 5.0+
          文件大小: ~20MB
        draft: false
        prerelease: false